spring.application.name=AdditivesManager


spring.datasource.url=jdbc:postgresql://localhost:5432/additives_manager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=199815ru

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

# Включить Flyway
spring.flyway.enabled=true

# Путь к миграциям (по умолчанию db/migration)
spring.flyway.locations=classpath:db/migration

# Очищать БД перед миграцией (только для dev!)
spring.flyway.clean-disabled=false

# Версионирование таблицы
spring.flyway.table=flyway_schema_history

# Кодировка
spring.flyway.encoding=UTF-8



jwt.secret=${JWT_SECRET:additives-manager-secret-key-32chars!!}

spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true